# Generated by Django 4.2.7 on 2025-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterparkapp', '0002_booking_razorpay_order_id_userprofile_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
