# Generated by Django 5.0.7 on 2025-03-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterparkapp', '0003_contact_inquiry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_phone_verified',
        ),
    ]
